# Generated by Django 6.1.1 on 2026-09-09 05:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('employment_category', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern'), ('temporary', 'Temporary'), ('other', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('job_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='organization.jobfamily')),
                ('job_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='organization.joblevel')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('unit_type', models.CharField(choices=[('corporate', 'Corporate'), ('region', 'Region'), ('area', 'Area'), ('business_unit', 'Business Unit'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_units', to='organization.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.organizationunit')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('location_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('office', 'Office'), ('warehouse', 'Warehouse'), ('training_center', 'Training Center'), ('other', 'Other')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('opened_on', models.DateField(blank=True, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('organization_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organization.organizationunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organization.location')),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organization.organizationunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('position_type', models.CharField(choices=[('individual_contributor', 'Individual Contributor'), ('supervisory', 'Supervisory'), ('management', 'Management')], default='individual_contributor', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('headcount_limit', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organization.department')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organization.job')),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organization.organizationunit')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='organization.position')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('restaurant_number', models.CharField(max_length=20, unique=True)),
                ('restaurant_type', models.CharField(choices=[('standalone', 'Standalone'), ('drive_thru', 'Drive-Thru'), ('mall_kiosk', 'Mall/Kiosk'), ('other', 'Other')], default='standalone', max_length=20)),
                ('operational_status', models.CharField(choices=[('operating', 'Operating'), ('temporarily_closed', 'Temporarily Closed'), ('under_renovation', 'Under Renovation'), ('closed', 'Closed'), ('planned', 'Planned')], default='planned', max_length=20)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant', to='organization.location')),
            ],
            options={
                'ordering': ['restaurant_number'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_family'], name='organizatio_job_fam_ef356d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_level'], name='organizatio_job_lev_2e2d07_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['code'], name='organizatio_code_39e49e_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['parent'], name='organizatio_parent__053983_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_19a2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['company', 'unit_type'], name='organizatio_company_a1807f_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationunit',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_org_unit_company_code'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type'], name='organizatio_locatio_094ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_a8f2b8_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['organization_unit'], name='organizatio_organiz_c8b5f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('closed_on__isnull', True), ('closed_on__gte', models.F('opened_on')), _connector='OR'), name='location_closed_on_after_opened_on'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='organizatio_code_320010_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent'], name='organizatio_parent__d9405f_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('location__isnull', True), ('organization_unit__isnull', False)), models.Q(('location__isnull', False), ('organization_unit__isnull', True)), _connector='OR'), name='department_exactly_one_anchor'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['code'], name='organizatio_code_8cfd5d_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['status'], name='organizatio_status_453a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['department'], name='organizatio_departm_b3a848_idx'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('headcount_limit__gte', 1)), name='position_headcount_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='position_effective_to_after_from'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['restaurant_number'], name='organizatio_restaur_00d406_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['operational_status'], name='organizatio_operati_0d7002_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('closing_date__isnull', True), ('closing_date__gte', models.F('opening_date')), _connector='OR'), name='restaurant_closing_date_after_opening_date'),
        ),
    ]
