# Generated by Django 6.1.1 on 2026-09-09 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('organization_unit', 'Organization Unit'), ('location', 'Location'), ('self', 'Self')], max_length=20)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.location')),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.organizationunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'scope_type'], name='accounts_us_user_id_1e692e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('location__isnull', True), ('organization_unit__isnull', True), ('scope_type', 'global')), models.Q(('location__isnull', True), ('organization_unit__isnull', False), ('scope_type', 'organization_unit')), models.Q(('location__isnull', False), ('organization_unit__isnull', True), ('scope_type', 'location')), models.Q(('location__isnull', True), ('organization_unit__isnull', True), ('scope_type', 'self')), _connector='OR'), name='userscope_fields_match_type')],
            },
        ),
    ]
