# Generated by Django 6.1.1 on 2026-09-09 08:52

import apps.employees.models.employee
import apps.employees.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Employee number sequence',
                'verbose_name_plural': 'Employee number sequence',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('employee_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], max_length=20)),
                ('nationality', models.CharField(blank=True, default='Pakistani', max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=apps.employees.models.employee._profile_photo_upload_path, validators=[apps.employees.validators.validate_profile_photo])),
                ('current_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee')),
                ('current_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_employees', to='organization.position')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child'), ('guardian', 'Guardian'), ('friend', 'Friend'), ('other', 'Other')], max_length=20)),
                ('mobile_number', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Emergency contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='Pakistan', max_length=100)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joining_date', models.DateField()),
                ('service_start_date', models.DateField(blank=True, help_text='Defaults to the joining date; differs only when past service counts toward seniority (e.g. a documented rehire adjustment).', null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern'), ('temporary', 'Temporary'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('probation', 'Probation'), ('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('direct', 'Direct'), ('dotted_line', 'Dotted Line')], default='direct', max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='employees.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_report_assignments', to='employees.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePositionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('acting', 'Acting'), ('temporary', 'Temporary'), ('additional_responsibility', 'Additional Responsibility')], max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_assignments', to='employees.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='organization.position')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_number'], name='employees_e_employe_e7cf1b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='employees_e_last_na_99a4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['current_position'], name='employees_e_current_974fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['current_manager'], name='employees_e_current_7a1c28_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(fields=['employee'], name='employees_e_employe_d3fdfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='emergencycontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('employee',), name='uniq_primary_emergency_contact_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeecontact',
            constraint=models.UniqueConstraint(condition=models.Q(('work_email', ''), _negated=True), fields=('work_email',), name='uniq_employee_contact_work_email'),
        ),
        migrations.AddIndex(
            model_name='employeeemployment',
            index=models.Index(fields=['status'], name='employees_e_status_7eaa08_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeemployment',
            constraint=models.CheckConstraint(condition=models.Q(('termination_date__isnull', True), ('termination_date__gte', models.F('joining_date')), _connector='OR'), name='employment_termination_after_joining'),
        ),
        migrations.AddConstraint(
            model_name='employeeemployment',
            constraint=models.CheckConstraint(condition=models.Q(('probation_end_date__isnull', True), ('probation_end_date__gte', models.F('joining_date')), _connector='OR'), name='employment_probation_end_after_joining'),
        ),
        migrations.AddIndex(
            model_name='employeemanagerassignment',
            index=models.Index(fields=['employee'], name='employees_e_employe_490014_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemanagerassignment',
            index=models.Index(fields=['manager'], name='employees_e_manager_1a31a0_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemanagerassignment',
            index=models.Index(fields=['employee', 'is_primary', 'end_date'], name='employees_e_employe_2fe9df_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeemanagerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_primary', True)), fields=('employee',), name='uniq_active_primary_manager_assignment_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeemanagerassignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='manager_assignment_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='employeemanagerassignment',
            constraint=models.CheckConstraint(condition=models.Q(('employee', models.F('manager')), _negated=True), name='manager_assignment_not_self'),
        ),
        migrations.AddIndex(
            model_name='employeepositionassignment',
            index=models.Index(fields=['employee'], name='employees_e_employe_edbcc0_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepositionassignment',
            index=models.Index(fields=['position'], name='employees_e_positio_e1f042_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepositionassignment',
            index=models.Index(fields=['employee', 'is_primary', 'end_date'], name='employees_e_employe_7e88ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeepositionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_primary', True)), fields=('employee',), name='uniq_active_primary_position_assignment_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeepositionassignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='position_assignment_end_after_start'),
        ),
    ]
